### ISSUE TITLE
Login returns HTTP 500 error in Chrome (dex branch)

### ISSUE THREAD

**Issue by whorka** [OSC/ood-images#18]
When I build and run the `docker-with-slurm` images, I am able to log in to http://localhost:8080 successfully when using Firefox or Safari, but I receive an HTTP 500 server error when using Chromium.

(This is on the `dex` branch, which @treydock [advised using](https://github.com/OSC/ondemand/issues/649#issuecomment-675012732) since dex is required in the default configuration of the latest OOD packages, 1.8.11.)

The error messages in `/var/log/httpd24/localhost_error.log` are:

```
[Mon Aug 17 18:34:16.449766 2020] [auth_openidc:warn] [pid 15] oidc_check_config_openid_openidc: the URL scheme (http) of the configured OIDCProviderMetadataURL SHOULD be "https" for security reasons!
[Mon Aug 17 18:34:16.449788 2020] [auth_openidc:warn] [pid 15] oidc_check_config_openid_openidc: the URL scheme (http) of the configured OIDCRedirectURI SHOULD be "https" for security reasons (moreover: some Providers may reject non-HTTPS URLs)
[Mon Aug 17 18:37:00.369212 2020] [auth_openidc:error] [pid 37] [client 172.22.0.1:58190] oidc_restore_proto_state: no "mod_auth_openidc_state_g0PdIli84RlUGZNPc6f8j3u_jNE" state cookie found, referer: http://localhost:5556/
[Mon Aug 17 18:37:00.369331 2020] [auth_openidc:error] [pid 37] [client 172.22.0.1:58190] oidc_unsolicited_proto_state: could not parse JWT from state: invalid unsolicited response: [src/jose.c:755: oidc_jwt_parse]: cjose_jws_import failed: invalid argument [file: jws.c, function: cjose_jws_import, line: 781], referer: http://localhost:5556/
[Mon Aug 17 18:37:00.369352 2020] [auth_openidc:error] [pid 37] [client 172.22.0.1:58190] oidc_authorization_response_match_state: unable to restore state, referer: http://localhost:5556/
[Mon Aug 17 18:37:00.369366 2020] [auth_openidc:error] [pid 37] [client 172.22.0.1:58190] oidc_handle_authorization_response: invalid authorization response state and no default SSO URL is set, sending an error..., referer: http://localhost:5556/
```

@treydock explained:
> The error you're getting is because there is a state cookie in your cache that is invalid and causing problems. I normally use Chrome for my day-to-day and when I saw this error I just switched to Firefox for this particular access and things worked fine. I've not yet had a chance to investigate if this is an issue with Chrome or just an issue with conflicting cache/cookie data that is fixed by clearing all cookie/cache data.

The error was not fixed by clearing cookies/cache or using an Incognito session.

**Comment by treydock** [comment]
This is seeming like an issue with Chrome's handling of `localhost` (and `127.0.0.1`) domain cookies.  This could also be an issue with Chrome and non-HTTPS sites and cookies because I've tried setting the container and access to use `ood.localhost.com` by updating `/etc/hosts` on my laptop and inside the container and still get 500 error.

It's worth noting that during PEARC20 we did a tutorial and had OnDemand running with Dex inside a container and it worked but that container was using HTTPS using a self signed CA.  We did not have this issue then and everything was accessed via `localhost` so I'm starting to think this maybe an issue with non-SSL access in Chrome.

**Comment by treydock** [comment]
@whorka I pushed some changes to dex branch that resolved the Chrome issue for me.  It turns out that Chrome now requires SameSite restrictions on non-SSL connections. I updated the configs for OnDemand to have mod_auth_openidc set `OIDCCookieSameSite On` which seems to have resolved my issue.

**Comment by whorka** [comment]
Confirmed, @treydock . Works for me. Thanks again for the quick response!

**Comment by treydock** [comment]
I am reverting those specific changes as ondemand 1.8.12 now sets `OIDCCookieSameSite On` by default when not using SSL.
